apiVersion: v1
kind: Service
metadata:
  name: userservice
  namespace: chatgut
spec:
  ports:
    - port: 8004
      targetPort: 8004
  selector:
    app: userservice
  clusterIP: None
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice
  labels:
    app: userservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userservice
  template:
    metadata:
      name: userservice
      labels:
        app: userservice
    spec:
      containers:
        - name: userservice
          image: urlshortenerservice2-app/name
          imagePullPolicy: Never
#          env:
#            - name: MYSQL_USER
#              value: developer
#            - name: MYSQL_PASSWORD
#              value: password
#            - name: DB_URL
#              value: jdbc:mysql://mysql:3306/demo
          ports:
            - containerPort: 8004
              name: userservice
      restartPolicy: Always