version: '3.8'

services:
  app:
    build:
      context: .
#    image: myimage:latest
    container_name: URLShortenerService2
#    depends_on:
#      mysql:
#        condition: service_healthy
    environment:
      DB_URL: jdbc:mysql://mysql:3306/demo
      DB_USER: developer
      DB_PASS: password
    ports:
      - "8004:8004"

  mysql:
    image: 'mysql:latest'
    container_name: mysqlDb
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: demo
      MYSQL_USER: developer
      MYSQL_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
#    healthcheck:
#      test: [ "CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER -p$$MYSQL_PASSWORD" ]
#      interval: 30s
#      timeout: 10s
#      retries: 5
  rabbitMQ:
    image: 'rabbitmq:3-management'
    container_name: QueueRabbitMQ
    volumes:
      - dbData:/var/lib/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"


volumes:
  db:
  dbData: